export const ogpDefaults = {
  titlePosition: "center",
  textAlign: "center",
  imagePosition: "center",
  fontFamily: "renewal",
  fontWeight: 800,
  tone: "dark",
};

export const ogpPages = [
  {
    id: "home",
    route: "/",
    pageType: "home",
    sourceTitle: "「やってみたい」を、形にする。",
    title: "「やってみたい」を、形にする。",
    heroImage: "/assets/hero/hero-pc.webp",
    brandImage: "/assets/brand/logoword-standard.png",
    templateType: "hero-direct",
    heroVariant: "home",
    titlePosition: "left",
    imagePosition: "center center",
    tone: "light",
    titleSize: 42,
    titleMaxWidth: 610,
    fontWeight: 700,
    fontFamily: "heading",
    outputName: "home.png",
    currentOgpPath: "/assets/og/og-top.png",
  },
  {
    id: "contents-index",
    route: "/contents",
    pageType: "contents-index",
    sourceTitle: "コンテンツ一覧",
    title: "コンテンツ一覧",
    heroImage: "/assets/eyecatch/contents-eyecatch.webp",
    templateType: "hero-direct",
    heroVariant: "image-only",
    tone: "light",
    outputName: "contents-index.png",
    currentOgpPath: "/assets/og/og-contents.png",
  },
  {
    id: "dictionary-hub",
    route: "/dictionary",
    pageType: "prompt-hub",
    sourceTitle: "プロンプト一覧",
    title: "プロンプト一覧",
    heroImage: "/assets/eyecatch/prompt-hub-eyecatch.webp",
    templateType: "hero-direct",
    heroVariant: "image-only",
    tone: "light",
    outputName: "dictionary.png",
    currentOgpPath: "/assets/og/og-prompt-hub.png",
  },
  {
    id: "prompt-list-hairstyle",
    route: "/dictionary/hairstyle",
    pageType: "prompt-list",
    sourceTitle: "髪型プロンプト一覧",
    title: "髪型プロンプト一覧",
    heroImage: "/assets/eyecatch/eyecatch-dictionary-hairstyle-bg-pc.webp",
    templateType: "hero-direct",
    heroVariant: "prompt-list",
    tone: "dark",
    titleSize: 58,
    titleMaxWidth: 900,
    fontFamily: "heading",
    fontWeight: 900,
    outputName: "prompt-list-hairstyle.png",
    currentOgpPath: "/assets/og/ogp-dictionary-hairstyle.png",
  },
  {
    id: "prompt-list-expression",
    route: "/dictionary/expression",
    pageType: "prompt-list",
    sourceTitle: "表情プロンプト一覧",
    title: "表情プロンプト一覧",
    heroImage: "/assets/eyecatch/eyecatch-dictionary-expression-bg-pc.webp",
    templateType: "hero-direct",
    heroVariant: "prompt-list",
    tone: "dark",
    titleSize: 58,
    titleMaxWidth: 900,
    fontFamily: "heading",
    fontWeight: 900,
    outputName: "prompt-list-expression.png",
    currentOgpPath: "/assets/og/ogp-dictionary-expression.png",
  },
  {
    id: "prompt-list-pose",
    route: "/dictionary/pose",
    pageType: "prompt-list",
    sourceTitle: "ポーズプロンプト一覧",
    title: "ポーズプロンプト一覧",
    heroImage: "/assets/eyecatch/eyecatch-dictionary-pose-bg-pc.webp",
    templateType: "hero-direct",
    heroVariant: "prompt-list",
    tone: "dark",
    titleSize: 58,
    titleMaxWidth: 900,
    fontFamily: "heading",
    fontWeight: 900,
    outputName: "prompt-list-pose.png",
    currentOgpPath: "/assets/og/ogp-dictionary-pose.png",
  },
  {
    id: "prompt-list-composition",
    route: "/dictionary/composition",
    pageType: "prompt-list",
    sourceTitle: "構図プロンプト一覧",
    title: "構図プロンプト一覧",
    heroImage: "/assets/eyecatch/eyecatch-dictionary-composition-bg-pc.webp",
    templateType: "hero-direct",
    heroVariant: "prompt-list",
    tone: "dark",
    titleSize: 58,
    titleMaxWidth: 900,
    fontFamily: "heading",
    fontWeight: 900,
    outputName: "prompt-list-composition.png",
    currentOgpPath: "/assets/og/ogp-dictionary-composition.png",
  },
  {
    id: "tool-anima-prompt-template",
    route: "/tools/anima-prompt-template",
    pageType: "tool",
    sourceTitle: "Animaでも使える!! AI発注書付きプロンプトガイドジェネレーター β",
    title: "プロンプトガイドジェネレーター β",
    titleLines: ["プロンプトガイド", "ジェネレーター β"],
    shortTitleStatus: "approved",
    heroImage: "/assets/eyecatch/eyecatch-tool-anima-prompt-template.webp",
    templateType: "hero-with-short-title",
    heroVariant: "content",
    imagePosition: "center 52%",
    tone: "dark",
    titleSize: 68,
    titleMaxWidth: 980,
    outputName: "tool-anima-prompt-template.png",
    currentOgpPath: "/assets/og/ogp-tool-anima-prompt-template.png",
  },
  {
    id: "article-anima-prompt-template-guide",
    route: "/articles/anima-prompt-template-guide",
    pageType: "article",
    sourceTitle:
      "Animaでも使えるプロンプトガイドジェネレーター βの使い方｜AI発注書と骨組みプロンプトの作り方",
    title: "プロンプトガイドジェネレーター β 使い方ガイド",
    titleLines: ["プロンプトガイドジェネレーター β", "使い方ガイド"],
    shortTitleStatus: "approved",
    heroImage: "/assets/eyecatch/eyecatch-tool-anima-prompt-template.webp",
    templateType: "hero-with-short-title",
    heroVariant: "content",
    imagePosition: "center 52%",
    tone: "dark",
    titleSize: 60,
    titleMaxWidth: 1040,
    outputName: "article-anima-prompt-template-guide.png",
    currentOgpPath: "/assets/og/ogp-article-anima-prompt-template-guide.png",
  },
  {
    id: "article-anima-basic",
    route: "/articles/anima-basic",
    pageType: "article",
    sourceTitle: "Animaとは？ComfyUIで試して感じた特徴と注意点",
    title: "Animaの特徴と注意点",
    titleLines: ["Animaの特徴と注意点"],
    shortTitleStatus: "approved",
    heroImage: "/assets/articles/anima-basic/anima-basic-02-two-girls.webp",
    templateType: "hero-with-short-title",
    heroVariant: "content",
    imagePosition: "62% 34%",
    tone: "dark",
    titleSize: 68,
    titleMaxWidth: 1040,
    outputName: "article-anima-basic.png",
    currentOgpPath: "/assets/og/og-anima-basic.png",
  },
  {
    id: "article-anima-style-compare",
    route: "/articles/anima-style-compare",
    pageType: "article",
    sourceTitle: "Animaの絵柄はどう変わる？スタイル系プロンプト10種類を作例で比較",
    title: "Anima｜スタイル10種比較",
    titleLines: ["Anima｜スタイル10種比較"],
    shortTitleStatus: "approved",
    heroImage: "/assets/articles/anima-style-compare/anima-style-scene-anime-screenshot.webp",
    templateType: "hero-with-short-title",
    heroVariant: "content",
    imagePosition: "58% 42%",
    tone: "dark",
    titleSize: 68,
    titleMaxWidth: 1040,
    outputName: "article-anima-style-compare.png",
    currentOgpPath: "/assets/og/ogp-anima-style-compare.png",
  },
  {
    id: "article-anima-prompt-writing",
    route: "/articles/anima-prompt-writing",
    pageType: "article",
    sourceTitle: "Animaで使える？プロンプトをタグと自然文で書く方法",
    title: "Anima｜タグ＋自然文の書き方",
    titleLines: ["Anima｜タグ＋自然文の書き方"],
    shortTitleStatus: "approved",
    heroImage: "/assets/articles/anima-prompt-writing/anima-prompt-single.webp",
    templateType: "hero-with-short-title",
    heroVariant: "content",
    imagePosition: "center top",
    tone: "dark",
    titleSize: 66,
    titleMaxWidth: 1040,
    outputName: "article-anima-prompt-writing.png",
    currentOgpPath: "/assets/og/ogp-anima-prompt-writing.png",
  },
  {
    id: "article-model-basic",
    route: "/articles/model-basic",
    pageType: "article",
    sourceTitle: "画像生成AIのモデルとは？SD1.5・SDXLの違いと選び方",
    title: "画像生成AIモデルの基本｜SD1.5・SDXL",
    titleLines: ["画像生成AIモデルの基本", "SD1.5・SDXL"],
    shortTitleStatus: "approved",
    heroImage: "/assets/articles/model-basic/model-basic-thumb.png",
    templateType: "hero-with-short-title",
    heroVariant: "content",
    imagePosition: "center top",
    tone: "dark",
    titleSize: 62,
    titleMaxWidth: 1040,
    outputName: "article-model-basic.png",
    currentOgpPath: "/assets/og/og-model-basic.png",
  },
  {
    id: "article-comfyui-start-guide",
    route: "/articles/comfyui-start-guide",
    pageType: "article",
    sourceTitle: "ComfyUIの始め方｜Portable版の導入から画像生成まで",
    title: "ComfyUIの始め方",
    titleLines: ["ComfyUIの始め方"],
    shortTitleStatus: "approved",
    heroImage: "/assets/articles/comfyui-start-guide/comfyui-start-guide-08-workflow-loaded.png",
    templateType: "hero-with-short-title",
    heroVariant: "content",
    imagePosition: "center",
    tone: "light",
    titleSize: 72,
    titleMaxWidth: 1040,
    outputName: "article-comfyui-start-guide.png",
    currentOgpPath: "/assets/og/og-comfyui-start-guide.png",
  },
  {
    id: "article-prompt-basic",
    route: "/articles/prompt-basic",
    pageType: "article",
    sourceTitle: "AIイラストのプロンプトとは？基本の考え方と書き方を整理する",
    title: "AIイラスト｜プロンプトの基本",
    titleLines: ["AIイラスト｜プロンプトの基本"],
    shortTitleStatus: "approved",
    heroImage: "/assets/articles/prompt-basic/prompt-basic-thumb.png",
    templateType: "hero-with-short-title",
    heroVariant: "content",
    imagePosition: "center",
    tone: "dark",
    titleSize: 66,
    titleMaxWidth: 1040,
    outputName: "article-prompt-basic.png",
    currentOgpPath: "/assets/og/og-prompt-basic.png",
  },
];
